# **Matrix-matrix multiplication**
This notebook register short examples of applying matrix-vector and matrix-matrix multiplication on a house pricing problem. It is not about model construction or validation, but simply to show the utility of those algebraic methods to predict values using an already known regression equation instead of doing loops on code.

This insight was gotten from [Andrew Ng's Machine Learning course on Coursera](https://www.coursera.org/learn/machine-learning).

# **Matrix-vector multiplication**
Assuming that a house price is defined by a linear regression equation $y=a+bx$,
where $x$ is the house squarefoot, we can write this equation parameters in a vector and multiply it by a given matrix (or list/vector) containing squarefoot data.


In [0]:
#First of all, let's import the tool we will use in notebook:
import numpy as np

#Equation parameters
a = 15000
b = 150

# vector and matrix creation:
equationVector = np.array([a,b])
houseSqftMatrix = np.array([[1,2104],[1,1416],[1,1534],[1,852]])

As we can see on the above cell, Sqfoot data matrix had to be appended with <b><i>1</i></b> in each row because something has to be multiplyed by the equation's intercept. Obviously, the intercept cannot be modifyed, so we use <b><i>1</i></b>.

Let's take a look at what we just created...

In [92]:
print("Equation's vector:")
print(equationVector)
print()
print("Squarefoot Data:")
print(houseSqftMatrix)

Equation's vector:
[15000   150]

Squarefoot Data:
[[   1 2104]
 [   1 1416]
 [   1 1534]
 [   1  852]]


To perform the multiplication, we simply use the ```numpy.dot``` function, as it goes below.



In [93]:
housePricesMatrix = np.dot(houseSqftMatrix, equationVector)
print(housePricesMatrix)

[330600 227400 245100 142800]


We could have used a loop ```for``` to perform the same operation. By this method, each row of ```houseSqftMatrix``` would input the equation directly, and an ```append()``` command would be needed to register each result in an array.

In [94]:
#Let's first remove the 1's from the Sqfoot data:
houseSqftList = houseSqftMatrix[:,1]

#Than we create an empty list to store each calculated price:
housePriceList = []

#Now let's input each value to the equation:
for element in houseSqftList:
  housePrice = a + b * element
  housePriceList.append(housePrice)
print(housePriceList)

[330600, 227400, 245100, 142800]


# **Matrix-matrix multiplication**
The same logic applies to matrix-matrix multiplication. For example, let's say we have three hypotesis of linear regression equations to predict prices of the same houses. In this case we should have a matrix (not a vector) of parameters for each equation in order to multiply it for the house prices matrix. Let's see the implementation of that.

In [95]:
#Assign parameters of the all equations to tuples to form a new array.
#Note that the array shape had to be modifyed so its number of columns matches
#the number of lines of Sqft matrix. This has to be done because of the matrix
#multiplication rule (mxn -> nxm).

intercepts = a, 13400, 17500
coefs = b, 120, 155
equationMatrix = np.array([intercepts, coefs])

#Mutiply Sqft by equations:
newHousePricesMatrix = np.dot(houseSqftMatrix, equationMatrix)
newHousePricesMatrix

array([[330600, 265880, 343620],
       [227400, 183320, 236980],
       [245100, 197480, 255270],
       [142800, 115640, 149560]])

Now let's try to do it using loop ```for```.

In [90]:
#The line below creates an empty np array of 'zero' lines and 3 columns. This is
#needed in order to concatenate vertically the vectors into a single array
#using 'np.vstack'later If we didn't do that, the first array will be 
#1-dimensioned and the second 3-dimensioned, causing a concatenation error.

housePricesMatrix_2 = np.empty((0,3), int)

#Now let's input each value each equation:
for element in houseSqftList:
  housePriceList_2 = []
  for j in range(0,3):
    housePrice = equationMatrix[0,j] + equationMatrix[1,j] * element
    housePriceList_2.append(housePrice)
  housePricesMatrix_2 = np.vstack((housePricesMatrix_2,housePriceList_2))
housePricesMatrix_2

array([[330600, 265880, 343620],
       [330600, 265880, 343620],
       [227400, 183320, 236980],
       [245100, 197480, 255270],
       [142800, 115640, 149560]])

Matrix operations demand less computational processing and can be substantially more efficient, faster, and easy to write than using loops instead.